### ISSUE TITLE
Add missing SharedAssemblyInfo to projects

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [Ruhrpottpatriot/GW2.NET#16]
Multiple projects are missing a reference to `SharedAssemblyInfo`, we either should add it, or move away from it altogether.

I'm personally more for a move away, since we can't increase the version of projects independently. We should be able to do that however.

**Comment by sliekens** [comment]
> I'm personally more for a move away, since we can't increase the version of projects independently. We should be able to do that however.

Why have independently versioned assemblies when all of the code is developed, built and released together? Release management is hard enough when you don't have to worry about version restrictions. Let's not make it harder.

**Comment by sliekens** [comment]
> Multiple projects are missing a reference to SharedAssemblyInfo

Do you mean the unit test projects? That's intentional.

**Comment by Ruhrpottpatriot** [comment]
With the changes in netcore2.0 a shared assembly info is no longer needed
#43
