### ISSUE TITLE
Missing mappings 1.3

### ISSUE THREAD

**Issue by sliekens** [Ruhrpottpatriot/GW2.NET#27]
This is a list of broken Json to object mappings that I found in version 1.3.0. It is probably incomplete and will be updated as I find more missing mappings.

Note: `_` means `unnamed` and refers to the root json object.
##### /v1/item_details.json
- `_.consumable.unlock_type` missing type "Outfit"
- `_.consumable.unlock_type` missing type "GliderSkin"
  - https://api.guildwars2.com/v1/item_details.json?item_id=67054
- `_.consumable.unlock_type` missing type "Champion"
  - https://api.guildwars2.com/v1/item_details.json?item_id=70076
- `_.consumable.type` missing type "TeleportToFriend"
  - https://api.guildwars2.com/v1/item_details.json?item_id=67280
- `_.consumable.skins` missing field
  - https://api.guildwars2.com/v1/item_details.json?item_id=8466
- `_.minipet.minipet_id` missing field
  - https://api.guildwars2.com/v1/item_details.json?item_id=20153
- `_.weapon.infix_upgrade.attributes.attribute` missing type "BoonDuration"
  - https://api.guildwars2.com/v1/item_details.json?item_id=74735
- `_.weapon.infix_upgrade.attributes.attribute` missing type "ConditionDuration"
  - https://api.guildwars2.com/v1/item_details.json?item_id=70918
- `_.consumable.extra_recipe_ids` missing field
  - https://api.guildwars2.com/v1/item_details.json?item_id=74301
##### /v2/items
- `_.details.unlock_type` missing type "Outfit"
- `_.details.unlock_type` missing type "GliderSkin"
  - https://api.guildwars2.com/v2/items/67054
- `_.details.unlock_type` missing type "Champion"
  - https://api.guildwars2.com/v2/items/70076
- `_.details.type` missing type "TeleportToFriend"
  - https://api.guildwars2.com/v2/items?id=67280
- `_.chat_link` missing field
- `_.details.skins` missing field
  - https://api.guildwars2.com/v2/items/8466
- `_.details.minipet_id` missing field
  - https://api.guildwars2.com/v2/items/20153
- `_.details.infix_upgrade.attributes.attribute` missing type "BoonDuration"
  - https://api.guildwars2.com/v2/items/74735
- `_.details.infix_upgrade.attributes.attribute` missing type "ConditionDuration"
  - https://api.guildwars2.com/v2/items/70918
- `_.details.extra_recipe_ids` missing field
  - https://api.guildwars2.com/v2/items/74301
##### /v1/recipe_details.json
- `_.type` missing type "LegendaryComponent"
  - https://api.guildwars2.com/v1/recipe_details?recipe_id=10000
- `_.type` missing type "GuildConsumableWvw"
  - https://api.guildwars2.com/v1/recipe_details?recipe_id=10184
##### /v2/recipes
- `_.chat_link` missing field
- `_.type` missing type "LegendaryComponent"
  - https://api.guildwars2.com/v2/recipes/10000
- `_.type` missing type "GuildConsumableWvw"
  - https://api.guildwars2.com/v2/recipes/10184
##### /v1/skin_details.json
- `_.type` missing type "Gathering"
  - https://api.guildwars2.com/v1/skin_details.json?skin_id=6055
  - https://api.guildwars2.com/v1/skin_details.json?skin_id=6063
  - https://api.guildwars2.com/v1/skin_details.json?skin_id=6075
##### /v2/skins
- `_.type` missing type "Gathering"
  - https://api.guildwars2.com/v2/skins?ids=6055,6063,6075
##### /v1/colors.json
- `_.item` missing field
- `_.categories` missing field
##### /v2/colors
- `_.item` missing field
- `_.categories` missing field
##### /v2/worlds
- `_.population` missing field
##### /v2/commerce/prices
- `_.whitelisted` missing field
##### Mumble Link
- `_.profession` missing mapping for value `9` (revenant)

**Comment by Ruhrpottpatriot** [comment]
as far as I can tell all of this is correct. and nothing is left out

**Comment by sliekens** [comment]
What about PvP and WvW stuff that they added with the expansion? Where's that?

**Comment by Ruhrpottpatriot** [comment]
Forgot to look into that, but it may be they haven't updated their API responses yet.

**Comment by sliekens** [comment]
Closed, with one important notice: gathering skins are only supported in version 2.
https://api.guildwars2.com/v2/skins?ids=6055,6063,6075

The same IDs should be available in version 1, but /v1/skin_details.json does not support gathering skins at the time of writing this.
https://api.guildwars2.com/v1/skin_details.json?skin_id=6055
https://api.guildwars2.com/v1/skin_details.json?skin_id=6063
https://api.guildwars2.com/v1/skin_details.json?skin_id=6075
