### ISSUE TITLE
Unable to retrieve backpack skins

### ISSUE THREAD

**Issue by sliekens** [Ruhrpottpatriot/GW2.NET#28]
The code has a precondition that backpack skins always have a details object, but backpack skins never have one. It's not possible right now to retrieve backpack skins.

**Comment by chrisjl154** [comment]
Where is the code for this? I'll have a pop at fixing this.

**Comment by sliekens** [comment]
The code is somewhere in this tree: https://github.com/Ruhrpottpatriot/GW2.NET/tree/v1.3.0
A fix is already waiting to be merged from: https://github.com/Ruhrpottpatriot/GW2.NET/tree/version1.4.0

**Comment by chrisjl154** [comment]
Ah ok thanks, I'll look for something else then.
