### ISSUE TITLE
SerializationException from Mumble Link

### ISSUE THREAD

**Issue by SamHurne** [Ruhrpottpatriot/GW2.NET#3]
When reading from the mumble link memory-mapped file, it is possible that the game client is writing to the file at the same time the library is reading from it. As a result, a SerializationException is thrown.

What should the behavior of the library be if that occurs? Catch it and try again? Catch it and return a null value? Catch it and re-throw?

**Comment by sliekens** [comment]
I'm not sure what the right behavior is. I think the right behavior is to throw an exception because this is an exceptional occurrence. So we're halfway there already. We just need to hide the `SerializationException` behind a custom exception (`MumbleException`?) so that our abstraction doesn't leak implementation details.

**Comment by SamHurne** [comment]
I think I agree, but I'm going to break down the options I initially listed with some additional brainstorming thoughts:

> - Catch it and try again

This is probably a bad choice. What if the GW2 client is messed up somehow, and we just continually try to re-read? Do we then have a maximum number of retries? What happens when we fail then?

> - Catch it and return a null value

This would work, but it's not clear why we returned a null value, and if a crash eventually happens, it's not clear why. If a developer doesn't handle the null value, then they may end up with a NullReferenceException somewhere down the line without any good context or reason.

> - Catch it and re-throw

Out of these 3 ideas, this definitely seems like the best option. As you stated, we can hide the internal implementation, the error can have a clear description with contextual information, and we can clearly document it with XML comments around the public methods.

**Comment by Ruhrpottpatriot** [comment]
I'm for a combination of 1 and 3. At first we should try it n-times, where n is a number the user can specify. After the nth try has failed we catch and rethrow the error.

**Comment by sliekens** [comment]
I opened an issue about this on the api-cdi page. Lye said that they will consider changing the game client to use a shared mutex object that you can use for synchronization.

https://github.com/arenanet/api-cdi/issues/98
