### ISSUE TITLE
Make collection properties not-nullable

### ISSUE THREAD

**Issue by sliekens** [Ruhrpottpatriot/GW2.NET#30]
Entities that have a collection property should initialize that property to an instance of an empty array. Property setters should throw when the given value is null. This is to avoid null reference exceptions when iterating over a collection property.

Example in class `InfixUpgrade`

``` c#
private static readonly CombatAttribute[] Empty = new CombatAttribute[0];
private ICollection<CombatAttribute> attributes = Empty;

public ICollection<CombatAttribute> Attributes
{
    get { return this.attributes; }
    set
    {
        if (value == null)
            throw new ArgumentNullException();
        this.attributes = value;
    }
}
```

The `Empty` array must be cached to avoid multiple object allocations.

**Comment by Ruhrpottpatriot** [comment]
Collection Properties should be read-only as per MS code guidelines. This allows individual items to be added or removed but the collection itself can't be changed. Your code should look about like this:

```
private static readonly CombatAttribute[] Empty = new CombatAttribute[0];
private ICollection<CombatAttribute> attributes = Empty;

public ICollection<CombatAttribute> Attributes
{
    get { return this.attributes; }
}
```

**Comment by sliekens** [comment]
The DTO converters require a public setter to `set` the converted collection. Changing that to list copy operations would degrade performance. Changing that to constructor arguments means not having a default constructor. I don't like either.

**Comment by sliekens** [comment]
PS: since this is gonna be a maintenance release, removing setters is out of the question.

In the same spirit, do not throw on null but fall back to the empty collection.

``` c#
private static readonly CombatAttribute[] Empty = new CombatAttribute[0];
private ICollection<CombatAttribute> attributes = Empty;

public ICollection<CombatAttribute> Attributes
{
    get { return this.attributes; }
    set
    {
        this.attributes = value ?? Empty;
    }
}
```

**Comment by Ruhrpottpatriot** [comment]
We can change that, for 1.4, but see #32 for a 2.0 change.
