### ISSUE TITLE
Regression in Paginator

### ISSUE THREAD

**Issue by sliekens** [Ruhrpottpatriot/GW2.NET#35]
**edit**
The `RetryOnFault()` addition to class `Paginator` introduced a threading issue in `FindAllPagesAsync()` that causes three errors:
- some pages are duplicated (same page is requested multiple times)
- other pages are skipped
- the page index goes out of range (last page index + 1)

**Comment by Ruhrpottpatriot** [comment]
Can you fix that? Or should I do it?

**Comment by sliekens** [comment]
**edit**: see updated first post
**original post**
I'm not sure if I understand what's happening.

It used to be possible to call `FindAllPagesAsync(int, int)` with the values of the `X-Page` headers of the first page, like so:

``` c#
// The first page has properties for PageSize and PageCount
var firstPage = await colors.FindPageAsync(pageIndex: 0);

// Use the X-Page values of the first page to get the rest of the pages
var allPages = await colors.FindAllPagesAsync(firstPage.PageSize, firstPage.PageCount);
```

Now the same code throws a service exception on the last request (page index out of range).

```
# first page
GET https://api.guildwars2.com/v2/colors?page=0
-> X-Page-Size:50
-> X-Page-Total:10

# last page
GET https://api.guildwars2.com/v2/colors?page_size=50&page=10
-> page out of range. Use page values 0 - 9.
```

The last page index should be 9 instead of 10, but has it always been like that?

It's possible that the API has always behaved like that, and that this bug entered the code when I updated class `Paginator` with retry logic and task interleaving.
- https://github.com/Ruhrpottpatriot/GW2.NET/blob/maintenance/src/GW2NET.Core/Common/Paginator.cs#L136
- https://github.com/Ruhrpottpatriot/GW2.NET/blob/maintenance/src/GW2NET.Core/Common/Paginator.cs#L148

The code looks like it's doing the right thing.

``` c#
for (var pageIndex = 0; pageIndex < pageCount; pageIndex++)
```

Maybe I'm going crazy...
