### ISSUE TITLE
How to get a list of any Items

### ISSUE THREAD

**Issue by Benjamin-Mathy** [Ruhrpottpatriot/GW2.NET#36]
hello ^^  i begin with your api. 
and you method FindAll()  for the items is unable :/ 

i try to get any items page but i have an expetion on the page 137.  the api say" precondition: value =! null" but when i do "if(xxxx.FindPage(137) != null )" , it's not ok :/ 

So , how can i get a list of any items ? :) 
thank you :P

**Comment by sliekens** [comment]
That exception message indicates a bug in our code. We're working on an
update.

PS: please use the `FindPageAsync` method. All non-async methods will be removed in a future version.

**Comment by Benjamin-Mathy** [comment]
i have still an exeption with "FindPageAsync" :/
when will you finish to correct this bug ?  i need it for my test in one weeks :/

PS:eventually i restart a new project on a new subject :S 

again thx for your work and your remark :P 

PS: you are belgium, can i use the french for the next ? :D

**Comment by sliekens** [comment]
English only, sorry.

We have everything ready for the next release, but it's not on NuGet yet.

If you absolutely can't wait then you can download the source code from the releases page: https://github.com/Ruhrpottpatriot/GW2.NET/releases/tag/v1.4.0

You can compile the code in Visual Studio 2012 or newer (Release | Any CPU).
Then copy `\src\GW2NET\bin\Release\*.dll` to your own project folder.
Then add a reference to every DLL that you copied to your project.

Or just wait until we update the NuGet packages and then you can update to v1.4.0 using the package manager.

**Comment by Benjamin-Mathy** [comment]
it is ok :P  
thank you so much ^^

**Comment by sliekens** [comment]
@dracolos you can use the nuget package manager in visual studio to update to a newer version (1.4.0) that doesn't have this problem.
