### ISSUE TITLE
Help getting started please

### ISSUE THREAD

**Issue by albert118** [Ruhrpottpatriot/GW2.NET#50]
Hi there, 
Not really sure if this is where to post this and ask a question being a bit inexperienced but here goes...

I've just been trying to startup the project by following the documentation [here](https://gw2dotnet.codeplex.com/documentation) and I can't get my head around some of the basics of the setup. 
I am inexperienced with C# and VS, I must be overlooking something quite simple though I think. 
So far I've attempted to set up the project by opening VS with the .NET desktop development, then opening a copy of the source code and opening the GW2.NET.sln file.

I have checked the references for GW2NET.dll and GW2NET.Core.dll (all there I'm pretty sure), and sure to build GW2NET.Tests and then I initialise interactive with project. Then I make sure to be using GW2NET and GW2NET.Common as the documentation says.
When I try to  create the variables for the facade class I get an error, 
`(1,10): error CS0103: The name 'GW2' does not exist in the current context`, after entering this, `var v1 = GW2.V1;`, whilst in the C# interactive console in VS (same for both).

Before this I had tried to attempt using the Items API, following the how to for returning a list of items ([here](https://gw2dotnet.codeplex.com/wikipage?title=Items&referringTitle=Documentation) and I get the same error about GW2 not existing in the current context.

I would love any help with this as it's something I'm very interested in learning about!

Other info:
-Running VS 2017
-.NET framework 4 - 4.6
-Windows 10 64 bit

**Comment by Ruhrpottpatriot** [comment]
You don't need to use the source code. The NuGet packages are the recommended way of referencing this library.
If that doesn't work, as the current implementation might be outdated, you download the most recent commit from the master branch. Then open then GW2.NET solution file and build it. Then you need to copy the compiled dlls to *your* project and add a reference to them. After that everything should work fine.

As for your error: It can't work for multiple reasons:
1. The V1 api should be pretty much disabled completely (we are going to remove the dlls for that in the next release).
2. From a quick glance over the most recent code, the class you are referencing is not name GW2 anymore its called `GW2Bootstrapper`, thus you need to write `var v2 = GW2Bootstrapper.V2` I'll update the documentation.

**Comment by albert118** [comment]
Ok thank you! 
This helps a lot thanks, I'd already had an inkling that it was the bootstrapper I needed to use  and not the GW2 namespace. I just hadn't fully put two and two together yet.

So as far as copying the completed dlls, where are these located once I've built the sln file? 
Also, by disabling the v1 api, should I simply not reference it?

*edit:
Figured out what my problem was, forgot to create a new instance of the bootstrapper class, all good now. Figured out pretty much everything now thanks!

```using System;
   using System.Collections.Generic;
   using System.Linq;
   using System.Text;
   using System.Threading.Tasks;
   using GW2NET;
   using GW2NET.Common;'

   namespace GW2apiItemDataLogger
   {
    
   public class Experiment1
    {

        static public void Main(string[] args)
        {
            GW2Bootstrapper boot = new GW2Bootstrapper();
            var v2 = boot.V2;
            var service = boot.V2.Items.ForDefaultCulture();
        
        // Get contextual information
        IPageContext ctx = service.FindPage(pageSize: 200, pageIndex: 0);

            // Iterate over all available pages
            foreach (var page in service.FindAllPages(ctx.PageSize, ctx.PageCount))
            {
                foreach (var item in page.Value)
                {
                    Console.WriteLine(item.Name);
                }
            }

        }
       
    }```

**Comment by Ruhrpottpatriot** [comment]
The compiled dlls are located in the "bin\{Configuration}" folder of each project.

**Comment by Ruhrpottpatriot** [comment]
Since no further requests came, I'm going to close this.
