### ISSUE TITLE
Mumble API is throwing NullReferenceException

### ISSUE THREAD

**Issue by GHOSCHT** [Ruhrpottpatriot/GW2.NET#58]
I've recently started playing around with the Mumble API and every time I want to get the map name, it throws a NullReferenceException. I got my game running and I'm standing right in Lions Arch. Can this be caused by the "virtual" property in the wrapper? I'm relatively inexperienced as I'm learning C# by myself in my freetime, so I have no experience with virtuals.

Here is my code snippet:
`string mapname = avatar.Identity.Map.MapName;`

**Comment by sliekens** [comment]
Hey @GHOSCHT, the Mumble implementation is pretty old at this point so it's possible that it is not up-to-date anymore with the current game client. Could you post a stacktrace?

**Comment by GHOSCHT** [comment]
Hey @StevenLiekens thanks for your answer. Here's the stacktrace you asked for: 
`Method: Void Main(System.String[])
 File: d:\Dokumente\Visual Studio 2017\Projects\GuildWars2Mumble\GuildWars2Mumble\Program.cs
 Line Number: 20` 
I haven't done it before, so I hope its sufficient for your needs. If you wanna take a look into my code here you go: [https://github.com/GHOSCHT/GuildWars2Mumble](https://github.com/GHOSCHT/GuildWars2Mumble)

**Comment by Seeker1437** [comment]
In your line where it says “catch”

Change it to `catch (Exception e)`

Then you can give us `e.ToString()`

**Comment by GHOSCHT** [comment]
Better? `System.NullReferenceException: Object reference not set to an instance of an object.
   at GuildWars2Mumble.Program.Main(String[] args) in d:\Dokumente\Visual Studio 2017\Projects\GuildWars2Mumble\GuildWars2Mumble\Program.cs:line 20` I also updated the repo to this approach.

**Comment by sliekens** [comment]
Yeah that's fine. Unfortunately stacktraces are pretty much useless for debugging NullReferenceException, but the repro is very handy.

**Comment by sliekens** [comment]
@GHOSCHT this is actually not a bug, just a questionable design.

The idea is that the Mumble library can work independently from the Maps library. For that reason, it will not download map info for you. It only provides a placeholder property.

What you can do is install the entire GW2NET (https://www.nuget.org/packages/GW2NET/) and then update your code like this.

```csharp
using System;
using System.Globalization;
using GW2NET;
using GW2NET.MumbleLink;

namespace GuildWars2Mumble
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var mumbler = MumbleLinkFile.CreateOrOpen())
            {
                var avatar = mumbler.Read();

                if (avatar != null)
                {
                    var maps = GW2.V2.Maps.ForCulture(CultureInfo.GetCultureInfo("en"));
                    avatar.Identity.Map = maps.Find(avatar.Identity.MapId);
                    Console.WriteLine(avatar.Identity.Map.MapName);
                    Console.ReadKey();
                }
            }
        }
    }
}
```

PS: .NET Core is not supported. GW2.NET only runs on .NET Framework. Change your `csproj` file:

```diff
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
-    <TargetFramework>netcoreapp2.1</TargetFramework>
+    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
+    <PackageReference Include="GW2NET" Version="1.4.0" />
    <PackageReference Include="GW2NET.MumbleLink" Version="1.4.0" />
  </ItemGroup>

</Project>

```
