### ISSUE TITLE
How to iterate over pages with custom Items?

### ISSUE THREAD

**Issue by RealFriesi** [Ruhrpottpatriot/GW2.NET#59]
Hey,
How can I get the item names of a custom list of item ids? I can not create pages to get the item names faster, item by item takes too long. I tried to extend the example in the wiki with LINQ queries to filter the items, but unfortunately I can not do it.

So, how can I create pages with my own itemids to iterate over the pages and items?

The wrapper is very useful and I use many things of it. But i do not get solved my problem described above 🤣

**Comment by sliekens** [comment]
If you have 200 ids or less, you can just do this:

```csharp
using System;
using GW2NET;

class Program
{
    static void Main(string[] args)
    {
        var items = GW2.V2.Items.ForCurrentUICulture();
        foreach (var item in items.FindAll(new[] { 24, 46, 56, ..., 200 }))
        {
            Console.WriteLine(item.Value.Name);
        }
    }
}
```

If you have more than 200, you have to split them into batches of max 200 ids.

Here's an example of how to do that with Interactive Extensions for .NET (https://www.nuget.org/packages/System.Interactive/)

```csharp
using System;
using System.Linq;
using GW2NET;

class Program
{
    static void Main(string[] args)
    {
        var items = GW2.V2.Items.ForCurrentUICulture();
        var ids = new[] { 24, 46, 56, ..., 200, ..., 400 };

        // Buffer explained: http://reactivex.io/documentation/operators/buffer.html
        var batchesOf200 = ids.Buffer(200);

        foreach (var batch in batchesOf200)
        foreach (var item in items.FindAll(batch))
        {
            Console.WriteLine(item.Value.Name);
        }
    }
}
```

Hope that helps.
